version: '3'

networks:
  backend_network:
    # Réseau privé pour les services backend
    internal: true
  frontend_network:
    driver: bridge

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybooksdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 20s
      retries: 10

  api:
    build: ./api
    expose:
      - "3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
      - frontend_network

  frontend:
    build: ./frontend
    ports:
      - "8889:80"
    depends_on:
      - api
    networks:
      - frontend_network

volumes:
  db_data:
